import "./globals.css";
import type { Metadata } from "next";
import { Eczar } from "next/font/google";
const eczar = Eczar({ subsets: ["latin"] });
import Script from "next/script";
import Header from "@/partials/Header";
import Footer from "@/partials/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-X9RZ58XPH1"
        strategy="afterInteractive"
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-X9RZ58XPH1');`}
      </Script>
      <Header />
      <div className="min-h-screen">{children}</div>
      <Footer />
    </html>
  );
}
